finleyjepson/T3A2-B-Frontend

package.json
postcss.config.js
src/App.jsx
src/index.css
tailwind.config.js

Followed **Install Tailwind CSS with Vite** (https://tailwindcss.com/docs/guides/vite) to initialise Tailwind CSS for the frontend.

build: initialised Tailwind CSS

---

src/App.jsx
tailwind.config.js

- Added a placeholder logo / title of app
- Added a login and sign up button
- Added placeholder nav bar

Header (Placeholder logo, signup / login buttons, nav bar)

---

src/App.jsx
src/components/Navbar.jsx
src/components/SignUp.jsx

- Initialised Sign Up (SignUp.jsx) component
- Created a mock sign up form
- Created the sign up form route in App.jsx

feat: created sign up form and route

---

src/App.jsx
src/components/Login.jsx
src/components/Navbar.jsx
src/components/SignUp.jsx

- Initialised Login (Login.jsx) component
- Added /login route
- Created a mock login form
- 'Login here' and 'Sign up here' prompts now link to the respective pages

feat: added login page; setup login/signup links

---

src/components/Navbar.jsx

Clicking the logo or app title at the top now links back to the home page.

feat: clicking logo/app title now links back to home

---

src/App.jsx
src/components/Home.jsx
src/components/PollContainer.jsx
src/components/SignUp.jsx

Embedded a poll to the home page using an iframe and https://strawpoll.com/

Embedded a poll to the home page

---

src/components/SignUp.jsx

- Added useState to Sign Up form to track initial state
- Added function to handle form changes
- Added function to submit username and password as JSON to POST /auth/register

feat: send sign up form data as json

---

src/components/Login.jsx
src/components/Navbar.jsx
src/components/PollContainer.jsx

- Fixed console log warnings for using allowTransparency
- Fixed console log warnings for nesting anchors in links

fix: console log warnings

---

src/components/Login.jsx
src/components/SignUp.jsx

- Added useState to Login form to track initial state
- Added function to handle Login form changes
- Added function to submit username and password as JSON to POST /auth/login

feat: login page username / password sends JSON

---

src/components/Login.jsx

- Successful login now retrieves accessToken and refreshToken
- Successful login now moves user back to home page through useNavigate()

feat: retrieving and storing login tokens

---

src/components/Login.jsx
src/components/SignUp.jsx

- Prevent sign up if passwords don't match
- Shows an error after submission if passwords don't match
- Redirect user to Home page after successful sign up

feat: sign up page behaviours (password, redirection)

---

src/components/Login.jsx

- Updated token storage from localStorage to sessionStorage

feat: changed token localStorage > sessionStorage

---

src/App.jsx
src/components/Login.jsx
src/components/Navbar.jsx

- Logging in now updates the navbar across the app
- Logout button now displayed when logged in
- Logout button removes tokens

feat: login reflected on navbar; added logout

---

src/App.jsx
src/components/SignUp.jsx

- Signing up now automatically logs that user in
- Upon successful sign up, navbar reflects login state with logout button

feat: successful sign up logs user in

---

.eslintrc.cjs
src/components/DropdownList.jsx
src/components/EventList.jsx
src/components/EventsLandingContainer.jsx

[NOT IMPLEMENTED], requires changes to backend

feat: Dropdown list with categories

---

src/components/Navbar.jsx

- Profile photo circle now appears when logged in
- Added menu dropdown menu profile photo is clicked

feat: profile photo / user menu when logged in

---

src/App.jsx
src/components/Login.jsx
src/components/Navbar.jsx

- Username now displays in profile menu 
- Sign out button now works as expected

feat: navbar / profile menu updates

---

src/components/SignUp.jsx

Added back in to SignUp.jsx:
```
// State variable for whether form is submitted (for password check)
const [formSubmitted, setFormSubmitted] = useState(false)
```

fix: sign-up page

---

src/App.jsx
src/components/SignUp.jsx

The username entered on sign up is now included in the profile dropdown on signup>login

feat: username changes in nav bar on sign up

---

src/components/Login.jsx

When user enters an incorrect username or password upon logging in, the form will now display an error.

feat: incorrect username/password prompt

---

src/components/CreateEvent.jsx

- Added access token to request body of Create Event
- Commented out `coords` for now as we need to fix the mapping of that between the backend (was breaking it)

feat: added token to event creation; fix event creation

---

src/App.jsx
src/components/UserProfile.jsx
src/components/navigation/Navbar.jsx

- Created profile page outline featuring sections for:
1. profile photo
2. upcoming events
3. favourite anime
4. favourite characters

feat: profile page outline

---

src/App.jsx
src/components/auth/Login.jsx
src/components/users/UserProfile.jsx

- The user's data should now pull correctly from the backend into the profile page. Well, at least the username works. (e.g. profile page should say 'Welcome, {username}!' if logged in

feat: user data now fetched from backend

---

src/App.jsx
src/components/navigation/ProfileDropdown.jsx
src/components/users/UserProfile.jsx

Grabbing username from backend now. This should be usable in things like Profile pages and the Profile dropdown menu.
However, need to figure out why this clears after a refresh.

feat: enabled username across profile, dropdown

---

src/components/navigation/ProfileDropdown.jsx

- 'Profile' button in profile dropdown now links to /profile
- Added correct user.username in profile dropdown so username now appears when logged in

Profile dropdown changes

---

src/components/navigation/ProfileDropdown.jsx

Commented out 'Settings' in dropdown and moved this feature to backlog.

feat: removed 'Settings' from profile dropdown

---

src/components/users/UserProfile.jsx

Attempted to write a function to update favourite characters on a given user. **Not working yet**

feat: update favourite characters (not working)

---

src/components/PollContainer.jsx

Poll was previously too squished and not appearing completely. Fixed the height so the poll is now appearing as expected.

fix: poll height

---

src/components/navigation/Navbar.jsx

Clicking 'Contact Us' in the navbar now opens a contact us modal

feat: contact us modal

---

src/App.jsx
src/components/navigation/ProfileDropdown.jsx
src/components/users/UserProfile.jsx

- Users can now add favourite characters to their profile
- This should persist in the backend 'characters' field and the frontend profile section

feat: can add characters to profile

---

src/components/users/UserProfile.jsx

- Users can now add favourite animes through the profile page
- Added remove buttons to current favourite animes / characters

Adding / removing favourite animes and characters

---

src/components/auth/SignUp.jsx
src/components/navigation/ProfileDropdown.jsx

Previously, when signing up, the newly created user would not be automatically signed in. Now, the user is signed in upon sign up.

fix: user logout and user sign up behaviour

---

src/components/navigation/Navbar.jsx

Previously 'Event' would also be active when visiting 'Create Event' page. This is no longer the case.

fix: Create Event link no longer also makes Event link active

---

package.json
src/tests/App.test.jsx
vite.config.js

- Added vitest package for unit testing on frontend
- Created tests folder > App.test.jsx
- Added some expect tests for Home, Navbar, Signup, Login

Initiated vitest and wrote some tests

---

src/tests/App.test.jsx

Added more testing for:
- Sign up button click
- Login button click
- User List rendering
- Create event form and button rendering
- User Profile and 'Add Favourite Anime' rendering

test: sign up/login button clicks, user list, create event, user profile

---

src/components/UpcomingAnimeContainer.jsx
src/components/events/UpcomingEvents.jsx
src/components/events/UpcomingEventsContainer.jsx
src/components/navigation/Navbar.jsx
src/components/navigation/ProfileDropdown.jsx

- Updated style of Upcoming Anime container
- Updated style of Upcoming Events container

Home page design changes

---

src/components/navigation/ProfileDropdown.jsx

Had an extra import from 'react' breaking the page

fix: redundant import

---

src/components/events/UpcomingEventsContainer.jsx
src/components/navigation/ProfileDropdown.jsx

Updated sign up button design

---

src/components/users/UserProfile.jsx

Previously the profile page boxes were squished when viewing on mobile resolutions. The boxes now stack nicely when viewing on mobile.

fix: made profile page more responsive on mobiles
